# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a75e7135aa8372fa78ae5fdb0c2deb395807a1c748737179aec1808d94ee517327b2def3edf1cb7b2943ce6391f17d3381eb1589cd3f148d54b792cdd3e2618

test:
  secret_key_base: a855cf21e95f532b6a905d63cd53f6cfe8f08e00b1ac474b478ef798465b6b74314f39dac511f651659a63dbf4de71e5b3fb75896e2a31fc937049f248aa4ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
